//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShabaFashionersLite.ServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseMessage", Namespace="http://schemas.datacontract.org/2004/07/ShabaLiteService")]
    [System.SerializableAttribute()]
    public partial class ResponseMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRef.IShabaLiteService")]
    public interface IShabaLiteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShabaLiteService/DoWork", ReplyAction="http://tempuri.org/IShabaLiteService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShabaLiteService/DoWork", ReplyAction="http://tempuri.org/IShabaLiteService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShabaLiteService/BackupData", ReplyAction="http://tempuri.org/IShabaLiteService/BackupDataResponse")]
        ShabaFashionersLite.ServiceRef.ResponseMessage BackupData(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShabaLiteService/BackupData", ReplyAction="http://tempuri.org/IShabaLiteService/BackupDataResponse")]
        System.Threading.Tasks.Task<ShabaFashionersLite.ServiceRef.ResponseMessage> BackupDataAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShabaLiteService/QueryBackups", ReplyAction="http://tempuri.org/IShabaLiteService/QueryBackupsResponse")]
        System.Collections.Generic.Dictionary<string, string> QueryBackups(string cred);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShabaLiteService/QueryBackups", ReplyAction="http://tempuri.org/IShabaLiteService/QueryBackupsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> QueryBackupsAsync(string cred);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShabaLiteService/GetBackup", ReplyAction="http://tempuri.org/IShabaLiteService/GetBackupResponse")]
        System.Collections.Generic.Dictionary<string, string> GetBackup(string BackUpID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShabaLiteService/GetBackup", ReplyAction="http://tempuri.org/IShabaLiteService/GetBackupResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetBackupAsync(string BackUpID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShabaLiteServiceChannel : ShabaFashionersLite.ServiceRef.IShabaLiteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShabaLiteServiceClient : System.ServiceModel.ClientBase<ShabaFashionersLite.ServiceRef.IShabaLiteService>, ShabaFashionersLite.ServiceRef.IShabaLiteService {
        
        public ShabaLiteServiceClient() {
        }
        
        public ShabaLiteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShabaLiteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShabaLiteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShabaLiteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public ShabaFashionersLite.ServiceRef.ResponseMessage BackupData(string id) {
            return base.Channel.BackupData(id);
        }
        
        public System.Threading.Tasks.Task<ShabaFashionersLite.ServiceRef.ResponseMessage> BackupDataAsync(string id) {
            return base.Channel.BackupDataAsync(id);
        }
        
        public System.Collections.Generic.Dictionary<string, string> QueryBackups(string cred) {
            return base.Channel.QueryBackups(cred);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> QueryBackupsAsync(string cred) {
            return base.Channel.QueryBackupsAsync(cred);
        }
        
        public System.Collections.Generic.Dictionary<string, string> GetBackup(string BackUpID) {
            return base.Channel.GetBackup(BackUpID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetBackupAsync(string BackUpID) {
            return base.Channel.GetBackupAsync(BackUpID);
        }
    }
}
